# Generated by Django 3.1.7 on 2021-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211104_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
